name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake --version
      - run: python --version
      - name: Install conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: Check conan version
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          conan --version
      - name: Configure
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          ./configure.sh
      - name: Build
        run: make 
        working-directory: Build
      - name: Run tests
        run: ./boost_optional_ext --log_level=message
        working-directory: Build/bin
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake --version
      - run: python --version
      - name: Install conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: conan install dependencies Windows
        run: |
          conan install . --build missing
      - name: Configure
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          ./configure_win.sh
        shell: bash 
      - name: Build
        run: |
          cmake --build ./Build --config Debug
        shell: bash
